<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" />
      <PackageReference Include="DotNetCore.CAP" />
      <PackageReference Include="DotNetCore.CAP.Dashboard" />
      <PackageReference Include="DotNetCore.CAP.PostgreSql" />
      <PackageReference Include="DotNetCore.CAP.RabbitMQ" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="MediatR" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FileFlow.Data\FileFlow.Data.csproj" />
      <ProjectReference Include="..\FileFlow.Shared\FileFlow.Shared.csproj" />
    </ItemGroup>

</Project>
